name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]

jobs:
  CLABot:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: "CLA Signature Bot"
        uses: roblox/cla-signature-bot@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: '.github/cla-signature/cla-v1.json'
          url-to-cladocument: 'https://github.com/scouten-adobe/cla-bot-testbed/blob/main/contributor-agreement.md'
          branch: 'main'
          whitelist: scouten-adobe,bot
          blockchain-storage-flag: false
